# Generated by Django 3.0.7 on 2020-06-12 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'celebrity'), (3, 'developer')])),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('jwt_secret', models.UUIDField(default=uuid.uuid4)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Joined on')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
